### ISSUE TITLE
he is harresaissing me

### ISSUE THREAD

**Issue by ungabunga1** [lawfull1/Group-Project-2#3]
please help me

**Comment by Sansation00** [comment]
womp womp

**Comment by ungabunga1** [comment]
ok😁

**Comment by ungabunga1** [comment]
💀

**Comment by ungabunga1** [comment]
![ClipWindowsGIF](https://github.com/lawfull1/Group-Project-2/assets/80986575/1df150c4-9fb3-4870-9178-a348a40a057b)

**Comment by ungabunga1** [comment]
![ClipWindowsGIF (2)](https://github.com/lawfull1/Group-Project-2/assets/80986575/f7b829e3-c298-4ff4-8af7-4879e670e3c0)

**Comment by ungabunga1** [comment]
![ClipWindowsGIF](https://github.com/lawfull1/Group-Project-2/assets/80986575/74dde00d-f360-4176-8d06-ab38a383e09a)

**Comment by ungabunga1** [comment]
I am still having this issue

**Comment by ungabunga1** [comment]
![ClipWindowsGIF](https://github.com/lawfull1/Group-Project-2/assets/80986575/5874d462-f48c-4833-9823-7c22dc433d3d)

**Comment by lawfull1** [comment]
![321303040-5874d462-f48c-4833-9823-7c22dc433d3d](https://github.com/lawfull1/Group-Project-2/assets/143927455/c7ae16ef-972b-48dd-8ba3-5c35c0afff4a)
