### ISSUE TITLE
![321303040-5874d462-f48c-4833-9823-7c22dc433d3d](https://github.com/lawfull1/Group-Project-2/assets/143927455/c7ae16ef-972b-48dd-8ba3-5c35c0afff4a)

### ISSUE THREAD

**Issue by ungabunga1** [lawfull1/Group-Project-2#5]
![321303040-5874d462-f48c-4833-9823-7c22dc433d3d](https://github.com/lawfull1/Group-Project-2/assets/143927455/c7ae16ef-972b-48dd-8ba3-5c35c0afff4a)

_Originally posted by @lawfull1 in https://github.com/lawfull1/Group-Project-2/issues/3#issuecomment-2047887348_

**Comment by lawfull1** [comment]
![321303040-5874d462-f48c-4833-9823-7c22dc433d3d](https://github.com/lawfull1/Group-Project-2/assets/143927455/f7bcf720-c0aa-43c6-acb7-22c5f07b1c91)

**Comment by ungabunga1** [comment]
![ClipWindowsGIF (2)](https://github.com/lawfull1/Group-Project-2/assets/80986575/0ddadf6d-43ef-4bf5-a4a9-61be0e11ad45)
